CREATE TABLE `competitor` (
  `ID` bigint(20) NOT NULL,
  `DISQUALIFIED` tinyint(1) NOT NULL DEFAULT '0',
  `DIVISION` varchar(255) NOT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `IPSCALIAS` varchar(255) DEFAULT NULL,
  `LASTNAME` varchar(255) NOT NULL,
  `POWERFACTOR` int(11) DEFAULT NULL,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `SHOOTERNUMBER` int(11) NOT NULL,
  `SQUAD` int(11) DEFAULT NULL,
  `TEAM` varchar(255) DEFAULT NULL,
  `MATCH_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE `competitor_categories` (
  `Competitor_ID` bigint(20) DEFAULT NULL,
  `CATEGORIES` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `ipscmatch` (
  `ID` bigint(20) NOT NULL,
  `DATE` date DEFAULT NULL,
  `LEVEL` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `STATUS` int(11) DEFAULT NULL,
  `UPLOADEDBYADMIN` tinyint(1) DEFAULT '0',
  `USER_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;


CREATE TABLE `ipscmatch_competitor` (
  `Match_ID` bigint(20) NOT NULL,
  `competitors_ID` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `matchresultdata` (
  `ID` bigint(20) NOT NULL,
  `DIVISION` varchar(255) DEFAULT NULL,
  `MATCH_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `matchresultdataline` (
  `ID` bigint(20) NOT NULL,
  `POINTS` double DEFAULT NULL,
  `RANK` int(11) DEFAULT NULL,
  `SCOREPERCENTAGE` double DEFAULT NULL,
  `SCOREDSTAGES` int(11) DEFAULT NULL,
  `COMPETITOR_ID` bigint(20) DEFAULT NULL,
  `MATCHRESULTDATA_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `match_divisions` (
  `Match_ID` bigint(20) DEFAULT NULL,
  `DIVISIONS` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `match_divisionswithresults` (
  `Match_ID` bigint(20) DEFAULT NULL,
  `DIVISIONSWITHRESULTS` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `scorecard` (
  `ID` bigint(20) NOT NULL,
  `AHITS` int(11) DEFAULT NULL,
  `ADDITIONALPENALTIES` int(11) DEFAULT NULL,
  `CHITS` int(11) DEFAULT NULL,
  `DHITS` int(11) DEFAULT NULL,
  `HITFACTOR` double NOT NULL,
  `MISSES` int(11) DEFAULT NULL,
  `MODIFIED` datetime NOT NULL,
  `NOSHOOTHITS` int(11) DEFAULT NULL,
  `POINTS` int(11) NOT NULL,
  `POPPERHITS` int(11) NOT NULL,
  `POPPERMISSES` int(11) NOT NULL,
  `POPPERNOSHOOTHITS` int(11) DEFAULT NULL,
  `PROCEDURALPENALTIES` int(11) DEFAULT NULL,
  `STAGEPOINTS` int(11) DEFAULT NULL,
  `STAGERANK` int(11) DEFAULT NULL,
  `TIME` double NOT NULL,
  `COMPETITOR_ID` bigint(20) NOT NULL,
  `STAGE_ID` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `sequence` (
  `SEQ_NAME` varchar(50) NOT NULL,
  `SEQ_COUNT` decimal(38,0) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `stage` (
  `ID` bigint(20) NOT NULL,
  `MAXPOINTS` int(11) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `STAGENUMBER` int(11) NOT NULL,
  `MATCH_ID` bigint(20) NOT NULL,
  `stages_ORDER` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE `user` (
  `ID` bigint(20) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ENABLED` tinyint(1) DEFAULT '0',
  `FIRSTNAME` varchar(255) DEFAULT NULL,
  `LASTNAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `PHONE` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

ALTER TABLE `competitor`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_COMPETITOR_MATCH_ID` (`MATCH_ID`);

ALTER TABLE `competitor_categories`
  ADD KEY `FK_Competitor_CATEGORIES_Competitor_ID` (`Competitor_ID`);


ALTER TABLE `ipscmatch`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_IPSCMatch_USER_ID` (`USER_ID`);

ALTER TABLE `ipscmatch_competitor`
  ADD PRIMARY KEY (`Match_ID`,`competitors_ID`),
  ADD KEY `FK_IPSCMatch_COMPETITOR_competitors_ID` (`competitors_ID`);

ALTER TABLE `matchresultdata`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_MATCHRESULTDATA_MATCH_ID` (`MATCH_ID`);

ALTER TABLE `matchresultdataline`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_MATCHRESULTDATALINE_COMPETITOR_ID` (`COMPETITOR_ID`),
  ADD KEY `FK_MATCHRESULTDATALINE_MATCHRESULTDATA_ID` (`MATCHRESULTDATA_ID`);

ALTER TABLE `match_divisions`
  ADD KEY `FK_Match_DIVISIONS_Match_ID` (`Match_ID`);

ALTER TABLE `match_divisionswithresults`
  ADD KEY `FK_Match_DIVISIONSWITHRESULTS_Match_ID` (`Match_ID`);

ALTER TABLE `scorecard`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_SCORECARD_STAGE_ID` (`STAGE_ID`),
  ADD KEY `FK_SCORECARD_COMPETITOR_ID` (`COMPETITOR_ID`);


ALTER TABLE `sequence`
  ADD PRIMARY KEY (`SEQ_NAME`);


ALTER TABLE `stage`
  ADD PRIMARY KEY (`ID`),
  ADD KEY `FK_STAGE_MATCH_ID` (`MATCH_ID`);

ALTER TABLE `user`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `USERNAME` (`USERNAME`);

ALTER TABLE `competitor`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=909;

ALTER TABLE `ipscmatch`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

ALTER TABLE `scorecard`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT;

ALTER TABLE `stage`
  MODIFY `ID` bigint(20) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=43;

ALTER TABLE `competitor_categories`
  ADD CONSTRAINT `FK_Competitor_CATEGORIES_Competitor_ID` FOREIGN KEY (`Competitor_ID`) REFERENCES `competitor` (`ID`);


ALTER TABLE `ipscmatch_competitor`
  ADD CONSTRAINT `FK_IPSCMatch_COMPETITOR_Match_ID` FOREIGN KEY (`Match_ID`) REFERENCES `ipscmatch` (`ID`),
  ADD CONSTRAINT `FK_IPSCMatch_COMPETITOR_competitors_ID` FOREIGN KEY (`competitors_ID`) REFERENCES `competitor` (`ID`);


ALTER TABLE `matchresultdata`
  ADD CONSTRAINT `FK_MATCHRESULTDATA_MATCH_ID` FOREIGN KEY (`MATCH_ID`) REFERENCES `ipscmatch` (`ID`);


ALTER TABLE `matchresultdataline`
  ADD CONSTRAINT `FK_MATCHRESULTDATALINE_COMPETITOR_ID` FOREIGN KEY (`COMPETITOR_ID`) REFERENCES `competitor` (`ID`),
  ADD CONSTRAINT `FK_MATCHRESULTDATALINE_MATCHRESULTDATA_ID` FOREIGN KEY (`MATCHRESULTDATA_ID`) REFERENCES `matchresultdata` (`ID`);


ALTER TABLE `match_divisions`
  ADD CONSTRAINT `FK_Match_DIVISIONS_Match_ID` FOREIGN KEY (`Match_ID`) REFERENCES `ipscmatch` (`ID`);

ALTER TABLE `match_divisionswithresults`
  ADD CONSTRAINT `FK_Match_DIVISIONSWITHRESULTS_Match_ID` FOREIGN KEY (`Match_ID`) REFERENCES `ipscmatch` (`ID`);

ALTER TABLE `scorecard`
  ADD CONSTRAINT `FK_SCORECARD_COMPETITOR_ID` FOREIGN KEY (`COMPETITOR_ID`) REFERENCES `competitor` (`ID`),
  ADD CONSTRAINT `FK_SCORECARD_STAGE_ID` FOREIGN KEY (`STAGE_ID`) REFERENCES `stage` (`ID`);
