CREATE TABLE IF NOT EXISTS `competitor` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `FIRSTNAME` varchar(255) NOT NULL,
  `LASTNAME` varchar(255) NOT NULL,
  `IPSCALIAS` varchar(255) DEFAULT NULL,
  `DIVISION` varchar(255) NOT NULL,
  `SHOOTERNUMBER` int(11) NOT NULL,
  `POWERFACTOR` int(11) DEFAULT NULL,  
  `DISQUALIFIED` tinyint(1) NOT NULL DEFAULT '0',
  `SQUAD` int(11) DEFAULT NULL,
  `TEAM` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `MATCH_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COMPETITOR_MATCH_ID` (`MATCH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `competitor_categories` (
  `Competitor_ID` bigint(20) NOT NULL,
  `CATEGORIES` varchar(255) NOT NULL,
  KEY `FK_Competitor_CATEGORIES_Competitor_ID` (`Competitor_ID`),
  CONSTRAINT `FK_Competitor_CATEGORIES_Competitor_ID` FOREIGN KEY (`Competitor_ID`) REFERENCES `competitor` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `ipscmatch` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `DATE` date DEFAULT NULL,
  `LEVEL` varchar(255) DEFAULT NULL,    
  `STATUS` int(11) DEFAULT NULL,
  `UPLOADEDBYADMIN` tinyint(1) DEFAULT '0',
  `USER_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_IPSCMatch_USER_ID` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;


CREATE TABLE IF NOT EXISTS `match_divisions` (
  `MATCH_ID` bigint(20) NOT NULL,
  `DIVISIONS` varchar(255) NOT NULL,
  KEY `FK_Match_DIVISIONS_Match_ID` (`Match_ID`),
  CONSTRAINT `FK_Match_DIVISIONS_Match_ID` FOREIGN KEY (`Match_ID`) REFERENCES `ipscmatch` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `stage` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PRACTISCOREID` varchar(36) DEFAULT NULL,
  `NAME` varchar(255) NOT NULL,
  `STAGENUMBER` int(11) NOT NULL,
  `MAXPOINTS` int(11) DEFAULT NULL,
  `MATCH_ID` bigint(20) NOT NULL,
  `stages_ORDER` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_STAGE_MATCH_ID` (`MATCH_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

CREATE TABLE IF NOT EXISTS `scorecard` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `AHITS` int(11) DEFAULT NULL,
  `CHITS` int(11) DEFAULT NULL,
  `DHITS` int(11) DEFAULT NULL,
  `MISSES` int(11) DEFAULT NULL,
  `NOSHOOTHITS` int(11) DEFAULT NULL,
  `PROCEDURALPENALTIES` int(11) DEFAULT NULL,
  `ADDITIONALPENALTIES` int(11) DEFAULT NULL,
  `TIME` double NOT NULL,
  `HITFACTOR` double NOT NULL,
  `POINTS` int(11) NOT NULL,
  `STAGERANK` int(11) DEFAULT NULL,
  `STAGEPOINTS` double DEFAULT NULL,
  `COMBINEDDIVISIONSTAGEPOINTS` double DEFAULT NULL,
  `SCOREPERCENTAGE` double DEFAULT NULL,
  `COMBINEDDIVISIONSCOREPERCENTAGE` double DEFAULT NULL,
  `DNF` boolean DEFAULT FALSE,
  `MODIFIED` datetime NOT NULL,
  `COMPETITOR_ID` bigint(20) NOT NULL,
  `STAGE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_SCORECARD_STAGE_ID` (`STAGE_ID`),
  KEY `FK_SCORECARD_COMPETITOR_ID` (`COMPETITOR_ID`),
  CONSTRAINT `FK_SCORECARD_COMPETITOR_ID` FOREIGN KEY (`COMPETITOR_ID`) REFERENCES `competitor` (`ID`),
  CONSTRAINT `FK_SCORECARD_STAGE_ID` FOREIGN KEY (`STAGE_ID`) REFERENCES `stage` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` varchar(255) DEFAULT NULL,
  `LASTNAME` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `ENABLED` tinyint(1) DEFAULT '0',
  `PHONE` varchar(255) DEFAULT NULL,
  `ROLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;